<a href="https://colab.research.google.com/github/ErkinboyevIxtiyor/ai-foundation/blob/develop/student_perfomance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("StudentsPerformance.csv")

print(f"Dataset shape (rows, columns): {df.shape}")
print(f"Column name: {df.columns.tolist()}")
print(f"First 5 rows of the dataset:")
print(df.head())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [5]:
print("Averge score bu subject:")
df[["math score", "reading score", "writing score"]].mean()

Averge score bu columns:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [6]:
print("Maximum score bu subject:")
df[["math score", "reading score", "writing score"]].max()

Maximum score bu subject:

math score       100
reading score    100
writing score    100
dtype: int64

In [7]:
print("minimum score bu subject:")
df[["math score", "reading score", "writing score"]].min()

minimum score bu subject:

math score        0
reading score    17
writing score    10
dtype: int64

In [8]:
print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()

Correlation:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000